language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo apt-get install gcc-arm-linux-gnueabihf 

before_script:
  - export DST_PROJECT=$PWD
  - echo $DST_PROJECT

script:
  - sudo chmod +x $DST_PROJECT/scripts/install_IceStorm.sh
  - sudo sh $DST_PROJECT/scripts/install_IceStorm.sh

  - cd $DST_PROJECT/
  - sudo wget -c https://raw.githubusercontent.com/RobertCNelson/tools/master/pkgs/dtc.sh
  - sudo chmod +x dtc.sh
  - sudo ./dtc.sh
   
  - cd $DST_PROJECT/examples/arm_blink_leds/fpga/
  - make
  - cd $DST_PROJECT/examples/arm_blink_leds/arm/
  - make

  - cd $DST_PROJECT/examples/blink_leds/
  - make

  - cd $DST_PROJECT/bridge_lib/
  - make

  - cd $DST_PROJECT/DTS
  - sudo dtc -O dtb -o BW-ICE40Cape-00A0.dtbo -b 0 -@ BW-ICE40Cape-00A0.dts

