language: c

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
install:
  - CC=gcc-4.8 CXX=g++-4.8 python

os:
  - linux

before_script:
  - export DST_PROJECT=$PWD
  - echo $DST_PROJECT

script:
  - sudo chmod +x $DST_PROJECT/scripts/install_IceStorm.sh
  - sudo sh $DST_PROJECT/scripts/install_IceStorm.sh

  - cd $DST_PROJECT/
  - sudo wget -c https://raw.githubusercontent.com/RobertCNelson/tools/master/pkgs/dtc.sh
  - sudo chmod +x dtc.sh
  - sudo ./dtc.sh
    
  - cd $DST_PROJECT/BW_Bridge/
  - make

  - cd $DST_PROJECT/example/
  - make synth

  - cd $DST_PROJECT/DTS
  - sudo dtc -O dtb -o ice40-overlay-00A0.dtbo -b 0 -@ ice40-overlay-00A0.dts
  - sudo dtc -O dtb -o bw-bridge-overlay-00A0.dtbo -b 0 -@ bw-bridge-overlay-00A0.dts
