language: c

os:
  - linux

before_install:
  - sudo apt-get update -qq
  
  - wget -c https://releases.linaro.org/components/toolchain/binaries/5.3-2016.02/arm-linux-gnueabihf/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf.tar.xz
  - tar xf gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf.tar.xz
  - export PATH=$PATH:$PWD/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/bin/
  - arm-linux-gnueabihf-gcc --version
  - sudo apt-get install python3
  - sudo apt-get install python
  - sudo apt-get install bc

before_script:
  - export DST_PROJECT=$PWD
  - sudo sh $DTS_PROJECT/scripts/install_IceStorm.sh

  - sudo wget -c https://raw.githubusercontent.com/RobertCNelson/tools/master/pkgs/dtc.sh
  - sudo chmod +x dtc.sh
  - sudo ./dtc.sh

script:
  - cd $DTS_PROJECT/BW_Bridge/
  - make

  - cd $DTS_PROJECT/example/
  - make synth

  - cd $DTS_PROJECT/DTS
  - sudo dtc -O dtb -o ice40-overlay-00A0.dtbo -b 0 -@ ice40-overlay-00A0.dts
  - sudo dtc -O dtb -o bw-bridge-overlay-00A0.dtbo -b 0 -@ bw-bridge-overlay-00A0.dts
